### ISSUE TITLE
How is this different from insert-css?

### ISSUE THREAD

**Issue by tomek-he-him** [bendrucker/insert-styles#1]
The API, functionality and [even](https://github.com/bendrucker/insert-styles/blob/efb4a2c59e053e824da892fdc1bffbf571851f32/index.js#L6-L7) [code](https://github.com/substack/insert-css/blob/acc7f4688a6e4b1ce2d5ebdbedb90e93385f991c/index.js#L4-L5) look very similar.

What we need and what’s not there in _insert-css_ are three things:
- https://github.com/substack/insert-css/pull/16
- https://github.com/substack/insert-css/pull/17
- https://github.com/substack/insert-css/pull/18

The reason: _[tape-css](https://github.com/studio-b12/tape-css)_. There’s some more background in the PRs themselves.

**Comment by bendrucker** [comment]
Yeah that's why it's mentioned in related. I wanted a version that ran in Node as a noop without having to screw around and make globals. I'll take all the PRs you linked to. Open em up here and I'll merge them.

**Comment by bendrucker** [comment]
To be a bit clearer: I wrote this intentionally to take no options with the intent to consider new options on a case-by-case basis by actively reviewing PRs.

**Comment by tomek-he-him** [comment]
:+1: Great news! Expect a couple of PRs today then!
