### ISSUE TITLE
Allow `options.id` to be passed in

### ISSUE THREAD

**Issue by ajoslin** [bendrucker/insert-styles#3]
I made a [fork of insert-css](https://github.com/ajoslin/insert-css/blob/master/index.js) that allows changes to existing CSS files to insert style contents into the same style element instead of creating a new one.

Then I made it so each time I insert styles via my transform, I pass in the filename as the id: https://github.com/ajoslin/stylin/blob/master/index.js#L67

This makes it so hot module reloading works: A reload of a JS file referencing a CSS file will cause the newest styles to be inserted into an existing `<style>` tag. 

It's hopeless to submit a PR to substack's insert-css, that project is unmaintained (~10 open PRs, some years old).

Here's what I would like:
- Allow id to be passed in to insert-styles, similar to [my fork of insert-css](https://github.com/ajoslin/insert-css/blob/master/index.js)
- Change stackcss to use insert-styles: [sheetify](https://github.com/stackcss/sheetify) and [css-extract](https://github.com/stackcss/css-extract).
- Have sheetify pass a filename, if given, as the `id` to insertStyles.

And now finally, hot module reload would work perfectly with the sheetify stack.

cc @yoshuawuyts

I can do all of the PRs if these ideas sound "OK" to you two.

**Comment by ajoslin** [comment]
I'm 99% sure neither of you @bendrucker or @yoshuawuyts use hot module reloading. I don't necessarily either, but for now I'm in a project that uses it. 

Either way, this idea of putting different styles into the same tag seems like a valid use case to support in general.

**Comment by bendrucker** [comment]
+1 from me, PR welcome!

**Comment by yoshuawuyts** [comment]
This sounds great!

**Comment by ahdinosaur** [comment]
yes, this will be awesome! thanks @ajoslin. :smile: 

happy to use `insert-styles` instead of `insert-css`. reminds me of https://github.com/davidguttman/cssify/pull/45#issuecomment-167863843. as in, `cssify` is using [this file](https://github.com/davidguttman/cssify/blob/master/lib/browser.js) instead of `insert-css`, where the difference is that their file takes in the id of the style tag, for the same purpose as mentioned here, so this makes sense for the `stackcss` ecosystem.

**Comment by ajoslin** [comment]
:+1: I have the code ready for a PR here, just having trouble getting the unit tests running. I opened a different issue for that.
