### ISSUE TITLE
Having trouble running unit tests in testron

### ISSUE THREAD

**Issue by ajoslin** [bendrucker/insert-styles#4]
I'm getting this (below) when trying to pipe the tests into `testron`. I'm having trouble finding anyone else with the same issue via google searches. You can see the SHA I'm on, with my npm/node versions in the screenshot:

![](http://ajoslin.co/1lE8u/1Y2TpxL9+)

I also tried Node v0.12 with no luck.

Ever bumped into this?

**Comment by bendrucker** [comment]
Tracked it down to a bad version of Electron
